## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __idiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov / v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __idiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov / v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 2) const keydeath = 0;
keydeath = _CGFW(lambda: [0], 1)[0]
# (Line 4) const bulletQ = 33;
bulletQ = _CGFW(lambda: [33], 1)[0]
# (Line 6) const tankType = 215;
tankType = _CGFW(lambda: [215], 1)[0]
# (Line 8) const Flag = 215;
Flag = _CGFW(lambda: [215], 1)[0]
# (Line 9) const shootNum = 23;
shootNum = _CGFW(lambda: [23], 1)[0]
# (Line 10) const maxbuildtime = 100;
maxbuildtime = _CGFW(lambda: [100], 1)[0]
# (Line 12) const Dragoon 	= 66;
Dragoon = _CGFW(lambda: [66], 1)[0]
# (Line 13) const Reaver 	= 83;
Reaver = _CGFW(lambda: [83], 1)[0]
# (Line 14) const Ursadon 	= 96;
Ursadon = _CGFW(lambda: [96], 1)[0]
# (Line 15) const Darchon 	= 63;
Darchon = _CGFW(lambda: [63], 1)[0]
# (Line 16) const Devourer 	= 46;
Devourer = _CGFW(lambda: [46], 1)[0]
# (Line 17) const Tank 		= 5;
Tank = _CGFW(lambda: [5], 1)[0]
# (Line 18) const Goliath 	= 3;
Goliath = _CGFW(lambda: [3], 1)[0]
# (Line 19) const Vulture 	= 2;
Vulture = _CGFW(lambda: [2], 1)[0]
# (Line 20) const Lurker 	= 103;
Lurker = _CGFW(lambda: [103], 1)[0]
# (Line 21) const Ultralisk = 39;
Ultralisk = _CGFW(lambda: [39], 1)[0]
# (Line 23) const List = [66, 83, 96, 63, 46, 5, 3, 2, 103, 39];
List = _CGFW(lambda: [_ARR(FlattenList([66, 83, 96, 63, 46, 5, 3, 2, 103, 39]))], 1)[0]
