## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __idiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov / v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __idiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov / v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import header;
import header
# (Line 2) import util.utilEud;
from util import utilEud
# (Line 3) import tank.tankAim;
from tank import tankAim
# (Line 4) import physics;
import physics
# (Line 7) const gravity = 1;
gravity = _CGFW(lambda: [1], 1)[0]
# (Line 8) const pTargetArray = EUDArray(10);
pTargetArray = _CGFW(lambda: [EUDArray(10)], 1)[0]
# (Line 9) var epdnum = 0;
epdnum = EUDCreateVariables(1)
_IGVA([epdnum], lambda: [0])
# (Line 11) function push(unitEpd)
# (Line 12) {
@EUDFunc
def f_push(unitEpd):
    # (Line 13) pTargetArray[epdnum] = unitEpd;
    _ARRW(pTargetArray, epdnum) << (unitEpd)
    # (Line 14) epdnum = epdnum + 1;
    epdnum << (epdnum + 1)
    # (Line 15) }
    # (Line 16) function popmid(unitEpd)

# (Line 17) {
@EUDFunc
def f_popmid(unitEpd):
    # (Line 18) for(var i=0; i<10; i++)
    i = EUDVariable()
    i << (0)
    if EUDWhile()(i >= 10, neg=True):
        def _t2():
            i.__iadd__(1)
        # (Line 19) {
        # (Line 20) if(pTargetArray[i] == unitEpd)
        if EUDIf()(pTargetArray[i] == unitEpd):
            # (Line 21) {
            # (Line 22) pTargetArray[i] = 0;
            _ARRW(pTargetArray, i) << (0)
            # (Line 23) epdnum = epdnum - 1;
            epdnum << (epdnum - 1)
            # (Line 24) }
            # (Line 25) }
        EUDEndIf()
        # (Line 26) }
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    # (Line 27) function boom(unitType, locID);

# (Line 28) function renderBullet()
# (Line 29) {//bullet physics
@EUDFunc
def f_renderBullet():
    # (Line 30) for(var i=0; i<10; i++)
    i = EUDVariable()
    i << (0)
    if EUDWhile()(i >= 10, neg=True):
        def _t2():
            i.__iadd__(1)
        # (Line 31) {
        # (Line 32) if(pTargetArray[i])
        if EUDIf()(pTargetArray[i]):
            # (Line 33) {
            # (Line 34) const locID = $L('locBullet');
            locID = GetLocationIndex('locBullet')
            # (Line 35) const unitEpd = pTargetArray[i];
            unitEpd = pTargetArray[i]
            # (Line 36) const unitType = utilEud.getUnitType(unitEpd);
            unitType = utilEud.f_getUnitType(unitEpd)
            # (Line 37) physics.renderUnit(unitEpd, 1);
            physics.f_renderUnit(unitEpd, 1)
            # (Line 38) MoveLocation(locID+1, unitType, $P7, $L('locDst')+1);
            DoActions(MoveLocation(locID + 1, unitType, 6, GetLocationIndex('locDst') + 1))
            # (Line 39) if(pTargetArray[0]) CenterView(locID+1);
            if EUDIf()(pTargetArray[0]):
                DoActions(CenterView(locID + 1))
                # (Line 41) if(Bring($P8, AtLeast, 1, '(buildings)', locID+1))
            EUDEndIf()
            if EUDIf()(Bring(7, AtLeast, 1, '(buildings)', locID + 1)):
                # (Line 42) {
                # (Line 43) popmid(unitEpd);
                f_popmid(unitEpd)
                # (Line 44) RemoveUnitAt(1, '(men)', locID+1, $P7);
                DoActions(RemoveUnitAt(1, '(men)', locID + 1, 6))
                # (Line 45) boom(unitType, locID);
                f_boom(unitType, locID)
                # (Line 46) }
                # (Line 47) else
                # (Line 48) {
            if EUDElse()():
                # (Line 49) const vx, vy = physics.getVxy(unitEpd);
                vx, vy = List2Assignable([physics.f_getVxy(unitEpd)])
                # (Line 50) physics.setVxy(unitEpd, vx, vy + gravity);
                physics.f_setVxy(unitEpd, vx, vy + gravity)
                # (Line 51) }
                # (Line 52) }
            EUDEndIf()
            # (Line 53) }
        EUDEndIf()
        # (Line 54) }
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    # (Line 56) const TOPSPEED = 28;

TOPSPEED = _CGFW(lambda: [28], 1)[0]
# (Line 57) const BOTSPEED = 4;
BOTSPEED = _CGFW(lambda: [4], 1)[0]
# (Line 58) function getBullet(unitType, num);
# (Line 59) function toggleBullet(unitEpd)
# (Line 60) {
@EUDFunc
def f_toggleBullet(unitEpd):
    # (Line 61) const unitType = utilEud.getUnitType(unitEpd);
    unitType = utilEud.f_getUnitType(unitEpd)
    # (Line 62) const player = utilEud.getPlayerID(unitEpd);
    player = utilEud.f_getPlayerID(unitEpd)
    # (Line 64) const nextQ = (utilEud.getDeath(player, header.bulletQ)+1)%2;
    nextQ = (utilEud.f_getDeath(player, header.bulletQ) + 1) % 2
    # (Line 65) SetDeaths(player, SetTo, nextQ, header.bulletQ);
    DoActions(SetDeaths(player, SetTo, nextQ, header.bulletQ))
    # (Line 66) const bullet = getBullet(unitType, nextQ);
    bullet = f_getBullet(unitType, nextQ)
    # (Line 68) utilEud.setBuildQueue1(unitEpd, bullet);
    utilEud.f_setBuildQueue1(unitEpd, bullet)
    # (Line 69) }
    # (Line 71) function makeBullet(unitType, x, y, angle, speed)

# (Line 72) {
@EUDFunc
def f_makeBullet(unitType, x, y, angle, speed):
    # (Line 73) const locID = $L('locBullet');
    locID = GetLocationIndex('locBullet')
    # (Line 74) utilEud.moveLocationXY(locID, x, y);
    utilEud.f_moveLocationXY(locID, x, y)
    # (Line 76) const unitEpd = epdread_epd(EPD(0x628438));
    unitEpd = f_epdread_epd(EPD(0x628438))
    # (Line 77) CreateUnitWithProperties(1, unitType, locID+1, $P7, UnitProperty(invincible = true));
    DoActions(CreateUnitWithProperties(1, unitType, locID + 1, 6, UnitProperty(invincible=True)))
    # (Line 80) const changedSpeed = TOPSPEED * speed/100 + BOTSPEED;
    changedSpeed = TOPSPEED * speed // 100 + BOTSPEED
    # (Line 81) const vx, vy = lengthdir(changedSpeed, angle);
    vx, vy = List2Assignable([f_lengthdir(changedSpeed, angle)])
    # (Line 82) physics.setVxy(unitEpd, vx, vy);
    physics.f_setVxy(unitEpd, vx, vy)
    # (Line 83) push(unitEpd);
    f_push(unitEpd)
    # (Line 84) }
    # (Line 86) function shoot(unitEpd)

# (Line 87) {
@EUDFunc
def f_shoot(unitEpd):
    # (Line 88) const x, y = utilEud.getUnitXY(unitEpd);
    x, y = List2Assignable([utilEud.f_getUnitXY(unitEpd)])
    # (Line 90) const speed = utilEud.getKillCount(unitEpd); //killcount
    speed = utilEud.f_getKillCount(unitEpd)
    # (Line 91) const angle = tankAim.getAngle(unitEpd);
    angle = tankAim.f_getAngle(unitEpd)
    # (Line 92) const dx, dy = lengthdir(32, angle);
    dx, dy = List2Assignable([f_lengthdir(32, angle)])
    # (Line 93) const targetPlayer = utilEud.getPlayerID(unitEpd);
    targetPlayer = utilEud.f_getPlayerID(unitEpd)
    # (Line 94) const unitType = utilEud.getUnitType(unitEpd);
    unitType = utilEud.f_getUnitType(unitEpd)
    # (Line 95) const bullet = getBullet(unitType, utilEud.getDeath(targetPlayer, header.bulletQ));
    bullet = f_getBullet(unitType, utilEud.f_getDeath(targetPlayer, header.bulletQ))
    # (Line 98) makeBullet(bullet, x+dx, y+dy, angle, speed);
    f_makeBullet(bullet, x + dx, y + dy, angle, speed)
    # (Line 99) }
    # (Line 101) function boom(unitType, locID)

# (Line 102) {
@EUDFunc
def f_boom(unitType, locID):
    # (Line 103) const bombUnit = 50;
    bombUnit = 50
    # (Line 104) const unitEpd = epdread_epd(EPD(0x628438));
    unitEpd = f_epdread_epd(EPD(0x628438))
    # (Line 105) CreateUnitWithProperties(1, bombUnit, locID+1, $P7, UnitProperty(invincible=true));
    DoActions(CreateUnitWithProperties(1, bombUnit, locID + 1, 6, UnitProperty(invincible=True)))
    # (Line 106) const unitPos = dwread_epd(unitEpd + 0x28/4);
    unitPos = f_dwread_epd(unitEpd + 0x28 // 4)
    # (Line 107) dwwrite_epd(unitEpd + 0x58/4, unitPos);
    f_dwwrite_epd(unitEpd + 0x58 // 4, unitPos)
    # (Line 108) utilEud.setOrderID(unitEpd, 135);
    utilEud.f_setOrderID(unitEpd, 135)
    # (Line 109) }
    # (Line 111) function getBullet(unitType, num)

# (Line 112) {
@EUDFunc
def f_getBullet(unitType, num):
    # (Line 113) if(unitType == header.Dragoon){
    if EUDIf()(unitType == header.Dragoon):
        # (Line 114) if(num) return 60;   //bullet1
        if EUDIf()(num):
            EUDReturn(60)
            # (Line 115) else    return 70;   //bullet2
        if EUDElse()():
            EUDReturn(70)
            # (Line 116) }
        EUDEndIf()
        # (Line 117) else if(unitType == header.Reaver){
    if EUDElseIf()(unitType == header.Reaver):
        # (Line 118) if(num) return 71;   //bullet1
        if EUDIf()(num):
            EUDReturn(71)
            # (Line 119) else    return 69;   //bullet2
        if EUDElse()():
            EUDReturn(69)
            # (Line 120) }
        EUDEndIf()
        # (Line 121) else if(unitType == header.Ursadon){
    if EUDElseIf()(unitType == header.Ursadon):
        # (Line 122) if(num) return 94;   //bullet1
        if EUDIf()(num):
            EUDReturn(94)
            # (Line 123) else    return 95;   //bullet2
        if EUDElse()():
            EUDReturn(95)
            # (Line 124) }
        EUDEndIf()
        # (Line 125) else if(unitType == header.Darchon){
    if EUDElseIf()(unitType == header.Darchon):
        # (Line 126) if(num) return 72;   //bullet1
        if EUDIf()(num):
            EUDReturn(72)
            # (Line 127) else    return 80;   //bullet2
        if EUDElse()():
            EUDReturn(80)
            # (Line 128) }
        EUDEndIf()
        # (Line 129) else if(unitType == header.Devourer){
    if EUDElseIf()(unitType == header.Devourer):
        # (Line 130) if(num) return 43;   //bullet1
        if EUDIf()(num):
            EUDReturn(43)
            # (Line 131) else    return 44;   //bullet2
        if EUDElse()():
            EUDReturn(44)
            # (Line 132) }
        EUDEndIf()
        # (Line 133) else if(unitType == header.Tank){
    if EUDElseIf()(unitType == header.Tank):
        # (Line 134) if(num) return 12;   //bullet1
        if EUDIf()(num):
            EUDReturn(12)
            # (Line 135) else    return 8;   //bullet2
        if EUDElse()():
            EUDReturn(8)
            # (Line 136) }
        EUDEndIf()
        # (Line 137) else if(unitType == header.Goliath){
    if EUDElseIf()(unitType == header.Goliath):
        # (Line 138) if(num) return 9;   //bullet1
        if EUDIf()(num):
            EUDReturn(9)
            # (Line 139) else    return 28;   //bullet2
        if EUDElse()():
            EUDReturn(28)
            # (Line 140) }
        EUDEndIf()
        # (Line 141) else if(unitType == header.Vulture){
    if EUDElseIf()(unitType == header.Vulture):
        # (Line 142) if(num) return 11;   //bullet1
        if EUDIf()(num):
            EUDReturn(11)
            # (Line 143) else    return 21;   //bullet2
        if EUDElse()():
            EUDReturn(21)
            # (Line 144) }
        EUDEndIf()
        # (Line 145) else if(unitType == header.Lurker){
    if EUDElseIf()(unitType == header.Lurker):
        # (Line 146) if(num) return 45;   //bullet1
        if EUDIf()(num):
            EUDReturn(45)
            # (Line 147) else    return 47;   //bullet2
        if EUDElse()():
            EUDReturn(47)
            # (Line 148) }
        EUDEndIf()
        # (Line 149) else if(unitType == header.Ultralisk){
    if EUDElseIf()(unitType == header.Ultralisk):
        # (Line 150) if(num) return 42;   //bullet1 overlord
        if EUDIf()(num):
            EUDReturn(42)
            # (Line 151) else    return 57;   //bullet2
        if EUDElse()():
            EUDReturn(57)
            # (Line 152) }
        EUDEndIf()
        # (Line 153) }
    EUDEndIf()
