## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __idiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov / v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __idiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov / v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import util.utilEud;
from util import utilEud
# (Line 2) import header;
import header
# (Line 3) import customText3 as ct;
import customText3 as ct
# (Line 8) function isSelecting()
# (Line 9) {
@EUDFunc
def f_isSelecting():
    # (Line 10) if(Bring($Force1, AtLeast, 1, header.Flag, $L('preTurn')+1)
    _t1 = EUDIf()
    # (Line 11) || Bring($Force3, AtLeast, 1, header.Flag, $L('preTurn')+1))
    if _t1(EUDSCOr()(Bring(18, AtLeast, 1, header.Flag, GetLocationIndex('preTurn') + 1))(Bring(20, AtLeast, 1, header.Flag, GetLocationIndex('preTurn') + 1))()):
        # (Line 12) return 1;
        EUDReturn(1)
        # (Line 13) else
        # (Line 14) return 0;
    if EUDElse()():
        EUDReturn(0)
        # (Line 15) }
    EUDEndIf()
    # (Line 17) function getSelection(targetPlayer)

# (Line 18) {
@EUDFunc
def f_getSelection(targetPlayer):
    # (Line 19) const selectedUnitEpd = dwread_epd_safe(EPD(0x6284E8 + 48*targetPlayer));
    selectedUnitEpd = f_dwread_epd_safe(EPD(0x6284E8 + 48 * targetPlayer))
    # (Line 20) if(selectedUnitEpd != 0)
    if EUDIf()(selectedUnitEpd == 0, neg=True):
        # (Line 21) {
        # (Line 22) const unitType = utilEud.getUnitType(EPD(selectedUnitEpd));
        unitType = utilEud.f_getUnitType(EPD(selectedUnitEpd))
        # (Line 23) return unitType;
        EUDReturn(unitType)
        # (Line 24) }
        # (Line 25) else
        # (Line 26) return 0;
    if EUDElse()():
        EUDReturn(0)
        # (Line 27) }
    EUDEndIf()
    # (Line 29) function showTankInfo(unitType, targetPlayer)

# (Line 30) {
@EUDFunc
def f_showTankInfo(unitType, targetPlayer):
    # (Line 33) if (unitType == 0)
    if EUDIf()(unitType == 0):
        # (Line 34) {
        # (Line 35) const chatPtr = dwread_epd(EPD(0x640B58));
        chatPtr = f_dwread_epd(EPD(0x640B58))
        # (Line 36) ct.printP(targetPlayer, ""); // ct.cp는 모두에게 출력
        ct.f_printP(targetPlayer, "")
        # (Line 37) ct.printP(targetPlayer, "\x13원하는 탱크를 마우스로 클릭해주세요");
        ct.f_printP(targetPlayer, "\x13원하는 탱크를 마우스로 클릭해주세요")
        # (Line 38) dwwrite_epd(EPD(0x640B58), chatPtr);
        f_dwwrite_epd(EPD(0x640B58), chatPtr)
        # (Line 39) }
        # (Line 40) else
        # (Line 41) {
    if EUDElse()():
        # (Line 42) const chatPtr = dwread_epd(EPD(0x640B58));
        chatPtr = f_dwread_epd(EPD(0x640B58))
        # (Line 44) if(unitType == header.Dragoon)
        if EUDIf()(unitType == header.Dragoon):
            # (Line 45) {
            # (Line 46) ct.printP(targetPlayer, ""); // ct.cp는 모두에게 출력
            ct.f_printP(targetPlayer, "")
            # (Line 47) ct.printP(targetPlayer, "\x13[ \x07빡탱\x01 ]");
            ct.f_printP(targetPlayer, "\x13[ \x07빡탱\x01 ]")
            # (Line 48) ct.printP(targetPlayer, "\x13공격: \x08■■■■□");
            ct.f_printP(targetPlayer, "\x13공격: \x08■■■■□")
            # (Line 49) ct.printP(targetPlayer, "\x03특징: \x01길 못찾음");
            ct.f_printP(targetPlayer, "\x03특징: \x01길 못찾음")
            # (Line 50) }
            # (Line 52) else if(unitType == header.Reaver)
        if EUDElseIf()(unitType == header.Reaver):
            # (Line 53) {
            # (Line 54) ct.printP(targetPlayer, ""); // ct.cp는 모두에게 출력
            ct.f_printP(targetPlayer, "")
            # (Line 55) ct.printP(targetPlayer, "\x13[ \x07빡탱\x01 ]");
            ct.f_printP(targetPlayer, "\x13[ \x07빡탱\x01 ]")
            # (Line 56) ct.printP(targetPlayer, "\x13공격: \x08■■■■□");
            ct.f_printP(targetPlayer, "\x13공격: \x08■■■■□")
            # (Line 57) ct.printP(targetPlayer, "\x03특징: \x01기어다님");
            ct.f_printP(targetPlayer, "\x03특징: \x01기어다님")
            # (Line 58) }
            # (Line 60) else if(unitType == header.Ursadon)
        if EUDElseIf()(unitType == header.Ursadon):
            # (Line 61) {
            # (Line 62) ct.printP(targetPlayer, ""); // ct.cp는 모두에게 출력
            ct.f_printP(targetPlayer, "")
            # (Line 63) ct.printP(targetPlayer, "\x13[ \x07빡탱\x01 ]");
            ct.f_printP(targetPlayer, "\x13[ \x07빡탱\x01 ]")
            # (Line 64) ct.printP(targetPlayer, "\x13공격: \x08■■■■□");
            ct.f_printP(targetPlayer, "\x13공격: \x08■■■■□")
            # (Line 65) ct.printP(targetPlayer, "\x03특징: \x01귀여움");
            ct.f_printP(targetPlayer, "\x03특징: \x01귀여움")
            # (Line 66) }
            # (Line 68) else if(unitType == header.Darchon)
        if EUDElseIf()(unitType == header.Darchon):
            # (Line 69) {
            # (Line 70) ct.printP(targetPlayer, ""); // ct.cp는 모두에게 출력
            ct.f_printP(targetPlayer, "")
            # (Line 71) ct.printP(targetPlayer, "\x13[ \x07빡탱\x01 ]");
            ct.f_printP(targetPlayer, "\x13[ \x07빡탱\x01 ]")
            # (Line 72) ct.printP(targetPlayer, "\x13공격: \x08■■■■□");
            ct.f_printP(targetPlayer, "\x13공격: \x08■■■■□")
            # (Line 73) ct.printP(targetPlayer, "\x03특징: \x01당하면 화남");
            ct.f_printP(targetPlayer, "\x03특징: \x01당하면 화남")
            # (Line 74) }
            # (Line 76) else if(unitType == header.Devourer)
        if EUDElseIf()(unitType == header.Devourer):
            # (Line 77) {
            # (Line 78) ct.printP(targetPlayer, ""); // ct.cp는 모두에게 출력
            ct.f_printP(targetPlayer, "")
            # (Line 79) ct.printP(targetPlayer, "\x13[ \x07딥탱\x01 ]");
            ct.f_printP(targetPlayer, "\x13[ \x07딥탱\x01 ]")
            # (Line 80) ct.printP(targetPlayer, "\x13공격: \x08■■■■□");
            ct.f_printP(targetPlayer, "\x13공격: \x08■■■■□")
            # (Line 81) ct.printP(targetPlayer, "\x03특징: \x01디바가 울면?");
            ct.f_printP(targetPlayer, "\x03특징: \x01디바가 울면?")
            # (Line 82) }
            # (Line 84) else if(unitType == header.Tank)
        if EUDElseIf()(unitType == header.Tank):
            # (Line 85) {
            # (Line 86) ct.printP(targetPlayer, ""); // ct.cp는 모두에게 출력
            ct.f_printP(targetPlayer, "")
            # (Line 87) ct.printP(targetPlayer, "\x13[ \x07탱크\x01 ]");
            ct.f_printP(targetPlayer, "\x13[ \x07탱크\x01 ]")
            # (Line 88) ct.printP(targetPlayer, "\x13공격: \x08■■■■□");
            ct.f_printP(targetPlayer, "\x13공격: \x08■■■■□")
            # (Line 89) ct.printP(targetPlayer, "\x03특징: \x01변신 못함");
            ct.f_printP(targetPlayer, "\x03특징: \x01변신 못함")
            # (Line 90) }
            # (Line 92) else if(unitType == header.Goliath)
        if EUDElseIf()(unitType == header.Goliath):
            # (Line 93) {
            # (Line 94) ct.printP(targetPlayer, ""); // ct.cp는 모두에게 출력
            ct.f_printP(targetPlayer, "")
            # (Line 95) ct.printP(targetPlayer, "\x13[ \x07골탱\x01 ]");
            ct.f_printP(targetPlayer, "\x13[ \x07골탱\x01 ]")
            # (Line 96) ct.printP(targetPlayer, "\x13공격: \x08■■■■□");
            ct.f_printP(targetPlayer, "\x13공격: \x08■■■■□")
            # (Line 97) ct.printP(targetPlayer, "\x03특징: \x01길 못찾음");
            ct.f_printP(targetPlayer, "\x03특징: \x01길 못찾음")
            # (Line 98) }
            # (Line 100) else if(unitType == header.Vulture)
        if EUDElseIf()(unitType == header.Vulture):
            # (Line 101) {
            # (Line 102) ct.printP(targetPlayer, ""); // ct.cp는 모두에게 출력
            ct.f_printP(targetPlayer, "")
            # (Line 103) ct.printP(targetPlayer, "\x13[ \x07벌탱\x01 ]");
            ct.f_printP(targetPlayer, "\x13[ \x07벌탱\x01 ]")
            # (Line 104) ct.printP(targetPlayer, "\x13공격: \x08■■■■□");
            ct.f_printP(targetPlayer, "\x13공격: \x08■■■■□")
            # (Line 105) ct.printP(targetPlayer, "\x03특징: \x01시벌탱");
            ct.f_printP(targetPlayer, "\x03특징: \x01시벌탱")
            # (Line 106) }
            # (Line 108) else if(unitType == header.Lurker)
        if EUDElseIf()(unitType == header.Lurker):
            # (Line 109) {
            # (Line 110) ct.printP(targetPlayer, ""); // ct.cp는 모두에게 출력
            ct.f_printP(targetPlayer, "")
            # (Line 111) ct.printP(targetPlayer, "\x13[ \x07럴탱\x01 ]");
            ct.f_printP(targetPlayer, "\x13[ \x07럴탱\x01 ]")
            # (Line 112) ct.printP(targetPlayer, "\x13공격: \x08■■■■□");
            ct.f_printP(targetPlayer, "\x13공격: \x08■■■■□")
            # (Line 113) ct.printP(targetPlayer, "\x03특징: \x01숨어있음");
            ct.f_printP(targetPlayer, "\x03특징: \x01숨어있음")
            # (Line 114) }
            # (Line 116) else if(unitType == header.Ultralisk)
        if EUDElseIf()(unitType == header.Ultralisk):
            # (Line 117) {
            # (Line 118) ct.printP(targetPlayer, ""); // ct.cp는 모두에게 출력
            ct.f_printP(targetPlayer, "")
            # (Line 119) ct.printP(targetPlayer, "\x13[ \x07울탱\x01 ]");
            ct.f_printP(targetPlayer, "\x13[ \x07울탱\x01 ]")
            # (Line 120) ct.printP(targetPlayer, "\x13공격: \x08■■■□□");
            ct.f_printP(targetPlayer, "\x13공격: \x08■■■□□")
            # (Line 121) ct.printP(targetPlayer, "\x03상식: \x01돼지는 하늘을 못본다");
            ct.f_printP(targetPlayer, "\x03상식: \x01돼지는 하늘을 못본다")
            # (Line 122) }
            # (Line 123) else
            # (Line 124) {
        if EUDElse()():
            # (Line 125) ct.printP(targetPlayer, ""); // ct.cp는 모두에게 출력
            ct.f_printP(targetPlayer, "")
            # (Line 126) ct.printP(targetPlayer, "\x13유닛을 마우스로 선택해주세요");
            ct.f_printP(targetPlayer, "\x13유닛을 마우스로 선택해주세요")
            # (Line 127) }
            # (Line 128) ct.printP(targetPlayer, "\x12\x07[ L ] : \x01선택");
        EUDEndIf()
        ct.f_printP(targetPlayer, "\x12\x07[ L ] : \x01선택")
        # (Line 129) dwwrite_epd(EPD(0x640B58), chatPtr);
        f_dwwrite_epd(EPD(0x640B58), chatPtr)
        # (Line 130) }
        # (Line 131) return unitType;
    EUDEndIf()
    EUDReturn(unitType)
    # (Line 132) }
    # (Line 134) function isListed(unitType)

# (Line 135) {
@EUDFunc
def f_isListed(unitType):
    # (Line 136) for(var i=0; i<10; i++)
    i = EUDVariable()
    i << (0)
    if EUDWhile()(i >= 10, neg=True):
        def _t2():
            i.__iadd__(1)
        # (Line 137) {
        # (Line 138) if(header.List[i] == unitType) return 1;
        if EUDIf()(header.List[i] == unitType):
            EUDReturn(1)
            # (Line 139) }
        EUDEndIf()
        # (Line 140) return 0;
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    EUDReturn(0)
    # (Line 141) }
    # (Line 143) function selectScreen()

# (Line 144) {
@EUDFunc
def f_selectScreen():
    # (Line 145) EUDPlayerLoop()();
    EUDPlayerLoop()()
    # (Line 146) const i = getcurpl();
    i = f_getcurpl()
    # (Line 147) if(i<6)
    if EUDIf()(i >= 6, neg=True):
        # (Line 148) {
        # (Line 150) if(Command(i, Exactly, 1, header.Flag))
        if EUDIf()(Command(i, Exactly, 1, header.Flag)):
            # (Line 151) {
            # (Line 152) const key = utilEud.getDeath(i, 0);
            key = utilEud.f_getDeath(i, 0)
            # (Line 153) CenterView($L('select')+1);
            DoActions(CenterView(GetLocationIndex('select') + 1))
            # (Line 154) const unitType = showTankInfo(getSelection(i), i);
            unitType = f_showTankInfo(f_getSelection(i), i)
            # (Line 156) if(key == 8 && isListed(unitType)) // L
            if EUDIf()(EUDSCAnd()(key == 8)(f_isListed(unitType))()):
                # (Line 157) {// confirm
                # (Line 158) RemoveUnit(header.Flag, i);
                DoActions(RemoveUnit(header.Flag, i))
                # (Line 160) SetDeaths(i, SetTo, unitType, header.tankType);
                DoActions(SetDeaths(i, SetTo, unitType, header.tankType))
                # (Line 161) }
                # (Line 163) }
            EUDEndIf()
            # (Line 164) }
        EUDEndIf()
        # (Line 165) EUDEndPlayerLoop();
    EUDEndIf()
    EUDEndPlayerLoop()
    # (Line 166) }
