## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __idiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov / v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __idiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov / v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) function moveLocationXY(locID, x, y) {
@EUDFunc
def f_moveLocationXY(locID, x, y):
    # (Line 2) dwwrite_epd(EPD(0x58DC60) + 5 * locID, x);
    f_dwwrite_epd(EPD(0x58DC60) + 5 * locID, x)
    # (Line 3) dwwrite_epd(EPD(0x58DC60) + 5 * locID + 1, y);
    f_dwwrite_epd(EPD(0x58DC60) + 5 * locID + 1, y)
    # (Line 4) dwwrite_epd(EPD(0x58DC60) + 5 * locID + 2, x);
    f_dwwrite_epd(EPD(0x58DC60) + 5 * locID + 2, x)
    # (Line 5) dwwrite_epd(EPD(0x58DC60) + 5 * locID + 3, y);
    f_dwwrite_epd(EPD(0x58DC60) + 5 * locID + 3, y)
    # (Line 6) }
    # (Line 8) function setpcolor(pnum, color) {

@EUDFunc
def f_setpcolor(pnum, color):
    # (Line 9) const pcolor_dst = 0x581D76 + 8 * pnum;
    pcolor_dst = 0x581D76 + 8 * pnum
    # (Line 10) const mcolor_dst = 0x581DD6 + pnum;
    mcolor_dst = 0x581DD6 + pnum
    # (Line 11) bwrite(pcolor_dst, color);
    f_bwrite(pcolor_dst, color)
    # (Line 12) bwrite(mcolor_dst, color);
    f_bwrite(mcolor_dst, color)
    # (Line 13) }
    # (Line 15) function getUnitXY(unitEpd)

# (Line 16) {
@EUDFunc
def f_getUnitXY(unitEpd):
    # (Line 17) return dwbreak(dwread_epd(unitEpd + 0x28/4));
    EUDReturn(f_dwbreak(f_dwread_epd(unitEpd + 0x28 // 4)))
    # (Line 18) }
    # (Line 20) function getOrderID(unitEpd)

# (Line 21) {
@EUDFunc
def f_getOrderID(unitEpd):
    # (Line 22) return dwbreak(dwread_epd(unitEpd + 0x4C / 4))[[3]];
    EUDReturn(f_dwbreak(f_dwread_epd(unitEpd + 0x4C // 4))[3])
    # (Line 23) }
    # (Line 25) function getPlayerID(unitEpd)

# (Line 26) {
@EUDFunc
def f_getPlayerID(unitEpd):
    # (Line 27) return dwbreak(dwread_epd(unitEpd + 0x4C / 4))[[2]];
    EUDReturn(f_dwbreak(f_dwread_epd(unitEpd + 0x4C // 4))[2])
    # (Line 28) }
    # (Line 30) function setOrderID(unitEpd, orderID)

# (Line 31) {
@EUDFunc
def f_setOrderID(unitEpd, orderID):
    # (Line 32) const player = getPlayerID(unitEpd);
    player = f_getPlayerID(unitEpd)
    # (Line 33) SetMemoryEPD(unitEpd + 0x4C / 4, SetTo, player + orderID * 256);
    DoActions(SetMemoryEPD(unitEpd + 0x4C // 4, SetTo, player + orderID * 256))
    # (Line 34) }
    # (Line 46) function getDeath(targetPlayer, targetUnit)

# (Line 47) {
@EUDFunc
def f_getDeath(targetPlayer, targetUnit):
    # (Line 48) for(var i=0; i<128; i++)
    i = EUDVariable()
    i << (0)
    if EUDWhile()(i >= 128, neg=True):
        def _t2():
            i.__iadd__(1)
        # (Line 49) if(Deaths(targetPlayer, Exactly, i, targetUnit))
        if EUDIf()(Deaths(targetPlayer, Exactly, i, targetUnit)):
            # (Line 50) return i;
            EUDReturn(i)
            # (Line 51) }
        EUDEndIf()
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
